version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupword
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - nlreturn
    - nolintlint
    - paralleltest
    - revive
    - testifylint
    - testpackage
    - varnamelen
    - wsl
  settings:
    lll:
      line-length: 100
      tab-width: 2
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Line contains TODO/BUG/FIXME
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
